# Generated by Django 2.2.6 on 2020-01-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guilduser',
            old_name='status',
            new_name='membership_type',
        ),
    ]
