from typing import Any, Dict, Optional

from django import forms

class JSONEditorWidget(forms.Widget):
    class Media:
        css: Any = ...
        js: Any = ...
    template_name: str = ...
    options: Any = ...
    width: Any = ...
    height: Any = ...
    def __init__(
        self,
        attrs: Optional[Any] = ...,
        mode: str = ...,
        options: Optional[Any] = ...,
        width: Optional[Any] = ...,
        height: Optional[Any] = ...,
    ) -> None: ...
    def get_context(self, name: Any, value: Any, attrs: Any) -> Dict[str, Any]: ...
