from typing import Any, Optional

from django.core.management import BaseCommand

class EmailNotificationCommand(BaseCommand):
    def add_arguments(self, parser: Any) -> None: ...
    argv_string: Any = ...
    def run_from_argv(self, argv: Any) -> None: ...
    def execute(self, *args: Any, **options: Any) -> None: ...
    def send_email_notification(
        self,
        notification_id: Optional[Any] = ...,
        include_traceback: bool = ...,
        verbosity: int = ...,
    ) -> None: ...
