from typing import Any

__contributors__: Any

def parse_file_or_list(arg: Any): ...

class ModelGraph:
    graphs: Any = ...
    cli_options: Any = ...
    disable_fields: Any = ...
    disable_abstract_fields: Any = ...
    include_models: Any = ...
    all_applications: Any = ...
    use_subgraph: Any = ...
    verbose_names: Any = ...
    inheritance: Any = ...
    relations_as_fields: Any = ...
    sort_fields: Any = ...
    language: Any = ...
    exclude_columns: Any = ...
    exclude_models: Any = ...
    hide_edge_labels: Any = ...
    arrow_shape: Any = ...
    app_labels: Any = ...
    def __init__(self, app_labels: Any, **kwargs: Any) -> None: ...
    def generate_graph_data(self) -> None: ...
    def get_graph_data(self, as_json: bool = ...): ...
    def add_attributes(self, field: Any, abstract_fields: Any): ...
    def add_relation(self, field: Any, model: Any, extras: str = ...): ...
    def get_abstract_models(self, appmodels: Any): ...
    def get_app_context(self, app: Any): ...
    def get_appmodel_attributes(self, appmodel: Any): ...
    def get_appmodel_abstracts(self, appmodel: Any): ...
    def get_appmodel_context(self, appmodel: Any, appmodel_abstracts: Any): ...
    def get_bases_abstract_fields(self, c: Any): ...
    def get_inheritance_context(self, appmodel: Any, parent: Any): ...
    def get_models(self, app: Any): ...
    def get_relation_context(
        self, target_model: Any, field: Any, label: Any, extras: Any
    ): ...
    def process_attributes(
        self, field: Any, model: Any, pk: Any, abstract_fields: Any
    ): ...
    def process_apps(self) -> None: ...
    def process_local_fields(self, field: Any, model: Any, abstract_fields: Any): ...
    def process_local_many_to_many(self, field: Any, model: Any): ...
    def process_parent(self, parent: Any, appmodel: Any, model: Any): ...
    def sort_model_fields(self, model: Any): ...
    def use_model(self, model_name: Any): ...
    def skip_field(self, field: Any): ...

def generate_dot(graph_data: Any, template: str = ...): ...
def generate_graph_data(*args: Any, **kwargs: Any): ...
def use_model(model: Any, include_models: Any, exclude_models: Any): ...
