import logging
from typing import Any, Optional

from django_extensions.management.signals import post_command as post_command
from django_extensions.management.signals import pre_command as pre_command

def setup_logger(
    logger: Any, stream: Any, filename: Optional[Any] = ..., fmt: Optional[Any] = ...
) -> None: ...

class RedirectHandler(logging.Handler):
    name: Any = ...
    logger: Any = ...
    def __init__(self, name: Any, level: Any = ...) -> None: ...
    def emit(self, record: Any) -> None: ...

def signalcommand(func: Any): ...
def has_ipdb(): ...
