from typing import Any

from django_extensions.mongodb.fields import AutoSlugField as AutoSlugField
from django_extensions.mongodb.fields import (
    CreationDateTimeField as CreationDateTimeField,
)
from django_extensions.mongodb.fields import (
    ModificationDateTimeField as ModificationDateTimeField,
)
from mongoengine.document import Document
from mongoengine.queryset import QuerySetManager

class TimeStampedModel(Document):
    created: Any = ...
    modified: Any = ...
    class Meta:
        abstract: bool = ...

class TitleSlugDescriptionModel(Document):
    title: Any = ...
    slug: Any = ...
    description: Any = ...
    class Meta:
        abstract: bool = ...

class ActivatorModelManager(QuerySetManager):
    def active(self): ...
    def inactive(self): ...

class ActivatorModel(Document):
    STATUS_CHOICES: Any = ...
    status: Any = ...
    activate_date: Any = ...
    deactivate_date: Any = ...
    objects: Any = ...
    class Meta:
        abstract: bool = ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
