version: '3.7'

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: django-admin runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
    - 8080:8080
    depends_on:
    - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hello_django:hello_django@postgres:5432/hello_django_dev
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: dev_only_password
    volumes:
      - ./migrations:/hasura-migrations

volumes:
  postgres_data:
