version: "3.7"

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build:
      context: .
      dockerfile: compose/development/Dockerfile
    command: django-admin runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./compose/development/.env.web
    depends_on:
      - postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    ports:
      - 8081:8080
    depends_on:
      - postgres
      - web
    restart: on-failure
    env_file:
      - ./compose/development/.env.hasura
    volumes:
      - ./hasura/metadata:/hasura-metadata

volumes:
  postgres_data:
