# Generated by Django 3.0.7 on 2020-06-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_auto_20200601_2151'),
        ('chronology', '0002_auto_20200624_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='meeting',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='notice_board.Meeting'),
            preserve_default=False,
        ),
    ]
