# Generated by Django 3.0.7 on 2020-06-26 07:12
from django.db import migrations
from django.db.models import JSONField

import chronology.models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology", "0003_auto_20200624_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="settings",
            field=JSONField(default=chronology.models.default_festival_settings),
        ),
    ]
