# Generated by Django 3.0.8 on 2020-07-04 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice_board', '0005_auto_20200626_1012'),
        ('chronology', '0004_auto_20200626_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='contact_info',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='name',
            field=models.CharField(default='Old Proposal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='CREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='notice_board.Meeting'),
        ),
    ]
