# Generated by Django 3.0.8 on 2020-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0005_auto_20200704_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='organizer',
            new_name='speaker_user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='speaker_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
