# Generated by Django 3.0.7 on 2020-06-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology", "0006_speaker_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="festival",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="chronology.Festival",
            ),
            preserve_default=False,
        ),
    ]
