# Generated by Django 3.0.8 on 2020-07-14 07:19

from django.db import migrations, models
from django.db.models import JSONField

import chronology.models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology", "0008_fix_json_default_and_agendaitem_table_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="club",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="needs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_contact",
            field=JSONField(default=chronology.models.default_json_field, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_data",
            field=JSONField(default=chronology.models.default_json_field, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
