# Generated by Django 3.0.8 on 2020-07-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0009_auto_20200714_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='contact_info',
        ),
    ]
