# Generated by Django 3.0.8 on 2020-07-18 18:17

from django.db import migrations, models

import chronology.models
import common.json_field


class Migration(migrations.Migration):

    dependencies = [
        ("chronology", "0010_remove_proposal_contact_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="topic",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
