# Generated by Django 3.0.8 on 2020-07-18 15:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import JSONField

import chronology.models


class Migration(migrations.Migration):

    dependencies = [
        ("notice_board", "0007_alter_sphere_site_related_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chronology", "0011_add_proposal_topic_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFestival",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("end_time", models.DateTimeField()),
                ("history_change_reason", models.TextField(null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "settings",
                    JSONField(default=chronology.models.default_festival_settings),
                ),
                ("slug", models.SlugField(blank=True)),
                ("start_proposal", models.DateTimeField()),
                ("start_publication", models.DateTimeField()),
                ("start_time", models.DateTimeField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sphere",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="notice_board.Sphere",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical festival",
                "db_table": "ch_festival_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
