# Generated by Django 3.0.8 on 2020-07-20 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chronology.models
import common.json_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notice_board", "0008_add_sphere_history"),
        ("chronology", "0012_add_festival_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendaitem",
            options={
                "verbose_name": "agenda item",
                "verbose_name_plural": "agenda items",
            },
        ),
        migrations.AlterModelOptions(
            name="festival",
            options={"verbose_name": "festival", "verbose_name_plural": "festivals"},
        ),
        migrations.AlterModelOptions(
            name="helper",
            options={"verbose_name": "helper", "verbose_name_plural": "helpers"},
        ),
        migrations.AlterModelOptions(
            name="proposal",
            options={"verbose_name": "proposal", "verbose_name_plural": "proposals"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "room", "verbose_name_plural": "rooms"},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"verbose_name": "time slot", "verbose_name_plural": "time slots"},
        ),
        migrations.AlterModelOptions(
            name="waitlist",
            options={"verbose_name": "waitlist", "verbose_name_plural": "waitlists"},
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="helper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chronology.Helper",
                verbose_name="helper",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="helper_confirmed",
            field=models.BooleanField(default=False, verbose_name="helper confirmed"),
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="meeting",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notice_board.Meeting",
                verbose_name="meeting",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="meeting_confirmed",
            field=models.BooleanField(default=False, verbose_name="meeting confirmed"),
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chronology.Room",
                verbose_name="room",
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="end_time",
            field=models.DateTimeField(verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="settings",
            field=common.json_field.PostgreSQLJSONField(
                default=chronology.models.default_festival_settings,
                verbose_name="settings",
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="sphere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Sphere",
                verbose_name="sphere",
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="start_proposal",
            field=models.DateTimeField(verbose_name="start proposal"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="start_publication",
            field=models.DateTimeField(verbose_name="start publication"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="start_time",
            field=models.DateTimeField(verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="helper",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chronology.Festival",
                verbose_name="festival",
            ),
        ),
        migrations.AlterField(
            model_name="helper",
            name="time_slots",
            field=models.ManyToManyField(
                to="chronology.TimeSlot", verbose_name="time slots"
            ),
        ),
        migrations.AlterField(
            model_name="helper",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="end_time",
            field=models.DateTimeField(verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="settings",
            field=common.json_field.PostgreSQLJSONField(
                default=chronology.models.default_festival_settings,
                verbose_name="settings",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="sphere",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="notice_board.Sphere",
                verbose_name="sphere",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="start_proposal",
            field=models.DateTimeField(verbose_name="start proposal"),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="start_publication",
            field=models.DateTimeField(verbose_name="start publication"),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="start_time",
            field=models.DateTimeField(verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="club",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="club"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="duration_minutes",
            field=models.PositiveIntegerField(verbose_name="duration minutes"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="meeting",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Meeting",
                verbose_name="meeting",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="needs",
            field=models.TextField(blank=True, null=True, verbose_name="needs"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_contact",
            field=common.json_field.PostgreSQLJSONField(
                default=chronology.models.default_json_field,
                null=True,
                verbose_name="other contact",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_data",
            field=common.json_field.PostgreSQLJSONField(
                default=chronology.models.default_json_field,
                null=True,
                verbose_name="other data",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="speaker_name",
            field=models.CharField(max_length=255, verbose_name="speaker name"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="speaker_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="speaker user",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="CREATED",
                max_length=15,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="time_slots",
            field=models.ManyToManyField(
                to="chronology.TimeSlot", verbose_name="time slots"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="topic",
            field=models.CharField(blank=True, max_length=255, verbose_name="topic"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="waitlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chronology.WaitList",
                verbose_name="waitlist",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chronology.Festival",
                verbose_name="festival",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.DateTimeField(verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chronology.Festival",
                verbose_name="festival",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.DateTimeField(verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="waitlist",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chronology.Festival",
                verbose_name="festival",
            ),
        ),
        migrations.AlterField(
            model_name="waitlist",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
