# Generated by Django 3.0.8 on 2020-07-21 18:09

from django.db import migrations


def make_char_fields_blank(apps, schema_editor):
    Proposal = apps.get_model("chronology", "Proposal")

    Proposal.objects.filter(city=None).update(city="")
    Proposal.objects.filter(club=None).update(club="")
    Proposal.objects.filter(needs=None).update(needs="")
    Proposal.objects.filter(phone=None).update(phone="")


def make_char_fields_null(apps, schema_editor):
    Proposal = apps.get_model("chronology", "Proposal")

    Proposal.objects.filter(city="").update(city=None)
    Proposal.objects.filter(club="").update(club=None)
    Proposal.objects.filter(needs="").update(needs=None)
    Proposal.objects.filter(phone="").update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ("chronology", "0013_locale"),
    ]

    operations = [migrations.RunPython(make_char_fields_blank, make_char_fields_null)]
