# Generated by Django 3.0.8 on 2020-07-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chronology.models
import common.json_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notice_board", "0010_blank_charfields"),
        ("chronology", "0014_blank_charfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaitem",
            name="helper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chronology.Helper",
                verbose_name="helper",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="meeting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notice_board.Meeting",
                verbose_name="meeting",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chronology.Room",
                verbose_name="room",
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="slug",
            field=models.SlugField(verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="historicalfestival",
            name="slug",
            field=models.SlugField(verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="club",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="club"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="meeting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Meeting",
                verbose_name="meeting",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="needs",
            field=models.TextField(blank=True, default="", verbose_name="needs"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_contact",
            field=common.json_field.JSONField(
                blank=True,
                default=chronology.models.default_json_field,
                verbose_name="other contact",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_data",
            field=common.json_field.JSONField(
                blank=True,
                default=chronology.models.default_json_field,
                verbose_name="other data",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="speaker_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="speaker user",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="topic",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="topic"
            ),
        ),
    ]
