# Generated by Django 3.0.8 on 2020-07-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0015_auto_20200721_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('unconfirmed', 'unconfirmed'), ('confirmed', 'confirmed')], default='unassigned', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='festival',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('proposal', 'proposal'), ('agenda', 'agenda'), ('ongoing', 'ongoing'), ('past', 'past')], default='draft', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalfestival',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('proposal', 'proposal'), ('agenda', 'agenda'), ('ongoing', 'ongoing'), ('past', 'past')], default='draft', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chronology.Room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_proposal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start proposal'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start publication'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='historicalfestival',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='historicalfestival',
            name='start_proposal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start proposal'),
        ),
        migrations.AlterField(
            model_name='historicalfestival',
            name='start_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start publication'),
        ),
        migrations.AlterField(
            model_name='historicalfestival',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
