# Generated by Django 3.0.8 on 2020-07-26 07:32

from django.db import migrations
from django.utils.text import slugify


def fill_slug_fields(apps, schema_editor):
    for model_name in ["Room", "WaitList"]:
        model = apps.get_model("chronology", model_name)
        for instance in model.objects.all():
            if not instance.slug:
                slug = slugify(instance.name)
                final_slug = slug
                i = 1
                while model.objects.filter(slug=final_slug).last():
                    final_slug = f"{slug}-{i}"
                    i += 1
                instance.slug = final_slug
                instance.save()


def purge_slug_fields(apps, schema_editor):
    for model_name in ["Room", "WaitList"]:
        model = apps.get_model("chronology", model_name)
        for instance in model.objects.all():
            if instance.slug:
                instance.slug = ""
                instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chronology", "0016_statuses_and_slugs"),
    ]

    operations = [migrations.RunPython(fill_slug_fields, purge_slug_fields)]
