# Generated by Django 3.0.8 on 2020-07-26 08:06

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0017_fill_slug_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.UniqueConstraint(fields=('sphere', 'slug'), name='festival_has_unique_slug_and_sphere'),
        ),
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_time__isnull', True), ('start_proposal__isnull', True), ('start_publication__isnull', True), ('start_time__isnull', True)), models.Q(('start_proposal__lte', django.db.models.expressions.F('start_publication')), ('start_publication__lte', django.db.models.expressions.F('start_time')), ('start_time__lt', django.db.models.expressions.F('end_time'))), _connector='OR'), name='festival_date_times'),
        ),
        migrations.AddConstraint(
            model_name='helper',
            constraint=models.UniqueConstraint(fields=('festival', 'user'), name='helper_has_unique_user_and_festival'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('slug', 'festival'), name='room_has_unique_slug_and_festival'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('festival', 'start_time', 'end_time'), name='timeslot_has_unique_times_for_festival'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(check=models.Q(start_time__lt=django.db.models.expressions.F('end_time')), name='timeslot_date_times'),
        ),
        migrations.AddConstraint(
            model_name='waitlist',
            constraint=models.UniqueConstraint(fields=('slug', 'festival'), name='waitlist_has_unique_slug_and_festival'),
        ),
    ]
