# Generated by Django 3.1 on 2020-08-11 17:28

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0018_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='festival',
            name='festival_date_times',
        ),
        migrations.AddField(
            model_name='festival',
            name='end_proposal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end proposal'),
        ),
        migrations.AddField(
            model_name='historicalfestival',
            name='end_proposal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end proposal'),
        ),
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_proposal__isnull', True), ('end_time__isnull', True), ('start_proposal__isnull', True), ('start_publication__isnull', True), ('start_time__isnull', True)), models.Q(('start_proposal__lte', django.db.models.expressions.F('end_proposal')), ('start_publication__lte', django.db.models.expressions.F('start_time')), ('start_time__lt', django.db.models.expressions.F('end_time'))), _connector='OR'), name='festival_date_times'),
        ),
    ]
