from typing import Any

from django.core.management.base import AppCommand
from django_extensions.management.utils import signalcommand as signalcommand

class Command(AppCommand):
    help: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    requires_system_checks: bool = ...
    can_import_settings: bool = ...
    def handle_app_config(self, app_config: Any, **options: Any) -> None: ...

def copy_template(template_name: Any, copy_to: Any, tag_library_name: Any) -> None: ...
