from typing import Any

from django.core.management.base import BaseCommand

REPLACES_REGEX: Any
PYC: str

def py_from_pyc(pyc_fn: Any): ...

class Command(BaseCommand):
    help: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    verbosity: Any = ...
    interactive: Any = ...
    dry_run: Any = ...
    def handle(self, **options: Any) -> None: ...
    def confirm(self): ...
    def find_migration(self, loader: Any, app_label: Any, name: Any): ...
