from typing import Any

from django.core.management.base import LabelCommand
from django_extensions.management.utils import signalcommand as signalcommand

class Command(LabelCommand):
    help: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any): ...

def describe_form(label: Any, fields: Any): ...
