from typing import Any

from django.core.management.base import LabelCommand
from django_extensions.management.utils import signalcommand as signalcommand

class Command(LabelCommand):
    help: str = ...
    args: str = ...
    label: str = ...
    def handle_label(self, template_path: Any, **options: Any) -> None: ...
