from typing import Any, Optional

from django.core.management.base import BaseCommand
from django_extensions.management.modelviz import ModelGraph as ModelGraph
from django_extensions.management.modelviz import generate_dot as generate_dot
from django_extensions.management.utils import signalcommand as signalcommand

HAS_PYGRAPHVIZ: bool
HAS_PYDOT: bool

class Command(BaseCommand):
    help: str = ...
    can_import_settings: bool = ...
    arguments: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any): ...
    def print_output(self, dotdata: Any, output_file: Optional[Any] = ...) -> None: ...
    def render_output_json(
        self, graph_data: Any, output_file: Optional[Any] = ...
    ) -> None: ...
    def render_output_pygraphviz(self, dotdata: Any, **kwargs: Any) -> None: ...
    def render_output_pydot(self, dotdata: Any, **kwargs: Any) -> None: ...
