from typing import Any

from django.core.management import BaseCommand
from django_extensions.management.utils import signalcommand as signalcommand

def get_model_to_deduplicate(): ...
def get_field_names(model: Any): ...
def keep_first_or_last_instance(): ...
def get_generic_fields(): ...

class Command(BaseCommand):
    help: str = ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    def merge_model_instances(self, primary_object: Any, alias_objects: Any): ...
