from typing import Any

from django.core.management.base import BaseCommand
from django_extensions.management.utils import signalcommand as signalcommand

class Command(BaseCommand):
    help: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    @staticmethod
    def include_attr(attr: Any, settings: Any): ...
    @staticmethod
    def print_simple(a_dict: Any) -> None: ...
