from typing import Any

from django.core.management.base import BaseCommand
from django_extensions.management.jobs import get_jobs as get_jobs
from django_extensions.management.jobs import print_jobs as print_jobs
from django_extensions.management.utils import setup_logger as setup_logger
from django_extensions.management.utils import signalcommand as signalcommand

logger: Any

class Command(BaseCommand):
    help: str = ...
    when_options: Any = ...
    def add_arguments(self, parser: Any) -> None: ...
    def usage_msg(self) -> None: ...
    def runjobs(self, when: Any, options: Any) -> None: ...
    def runjobs_by_signals(self, when: Any, options: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
