from typing import Any

from django_extensions.management.email_notifications import (
    EmailNotificationCommand as EmailNotificationCommand,
)
from django_extensions.management.utils import signalcommand as signalcommand

class DirPolicyChoices:
    NONE: str = ...
    EACH: str = ...
    ROOT: str = ...

def check_is_directory(value: Any): ...

class BadCustomDirectoryException(Exception):
    message: Any = ...
    def __init__(self, value: Any) -> None: ...

class Command(EmailNotificationCommand):
    help: str = ...
    current_directory: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any): ...
