from typing import Any

from django.core.management.base import BaseCommand
from django_extensions.management.utils import signalcommand as signalcommand

DEFAULT_FAKE_PASSWORD: str

class Command(BaseCommand):
    help: Any = ...
    requires_system_checks: bool = ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
