from typing import Any, Optional

from django.core.management.base import BaseCommand
from django_extensions.management.color import color_style as color_style
from django_extensions.management.color import no_style as no_style
from django_extensions.management.utils import signalcommand as signalcommand

class RegexURLPattern: ...
class RegexURLResolver: ...
class LocaleRegexURLResolver: ...

def describe_pattern(p: Any): ...

class URLPattern: ...
class URLResolver: ...

FMTR: Any

class Command(BaseCommand):
    help: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    LANGUAGES: Any = ...
    def handle(self, *args: Any, **options: Any): ...
    def extract_views_from_urlpatterns(
        self, urlpatterns: Any, base: str = ..., namespace: Optional[Any] = ...
    ): ...
