from typing import Any

from django.core.management import BaseCommand
from django_extensions.compat import load_tag_library as load_tag_library
from django_extensions.management.utils import signalcommand as signalcommand

def no_style(): ...
def color_style(): ...
def format_block(block: Any, nlspaces: int = ...): ...

class Command(BaseCommand):
    help: str = ...
    results: str = ...
    def add_result(self, s: Any, depth: int = ...) -> None: ...
    def handle(self, *args: Any, **options: Any): ...
