from typing import Any

from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help: str = ...
    requires_system_checks: bool = ...
    can_import_settings: bool = ...
    def add_arguments(self, parser: Any) -> None: ...
    style: Any = ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    def show_dsn(self, router: Any, options: Any) -> None: ...
