from typing import Any

from django.core.management.base import BaseCommand
from django_extensions.management.utils import signalcommand as signalcommand

def humanize(dirname: Any): ...

class SyncDataError(Exception): ...

class Command(BaseCommand):
    help: str = ...
    args: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    def remove_objects_not_in(self, objects_to_keep: Any, verbosity: Any) -> None: ...
    style: Any = ...
    using: Any = ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    def syncdata(self, fixture_labels: Any, options: Any) -> None: ...
