from typing import Any

from django.core.management.base import BaseCommand
from django_extensions.compat import get_template_setting as get_template_setting
from django_extensions.management.utils import signalcommand as signalcommand

class Command(BaseCommand):
    args: str = ...
    help: str = ...
    ignores: Any = ...
    def add_arguments(self, parser: Any) -> None: ...
    def ignore_filename(self, filename: Any): ...
    def handle(self, *args: Any, **options: Any) -> None: ...
