# Generated by Django 3.0.6 on 2020-06-06 08:42

from django.db import migrations


def add_default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.filter(id=1).update(
        name="Zagrajmy", domain="zagrajmy.net",
    )


def remove_default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.filter(id=1).update(
        name="example.com", domain="example.com",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_default_site, remove_default_site)]
