from typing import Any, Optional

def load_tag_library(libname: Any): ...
def get_template_setting(template_key: Any, default: Optional[Any] = ...): ...

class UnicodeWriter:
    queue: Any = ...
    writer: Any = ...
    stream: Any = ...
    encoder: Any = ...
    def __init__(
        self, f: Any, dialect: Any = ..., encoding: str = ..., **kwds: Any
    ) -> None: ...
    def writerow(self, row: Any) -> None: ...
    def writerows(self, rows: Any) -> None: ...
