from typing import Any, Dict, List, Tuple

class SubclassesFinder:
    base_classes: Any = ...
    def __init__(self, base_classes_from_settings: Any) -> None: ...
    def collect_subclasses(self) -> Dict[str, List[Tuple[str, str]]]: ...
