from typing import Any

BASE_DIR: Any
REPLACEMENTS: Any
DEFAULT_SQLITE_ENGINES: Any
DEFAULT_MYSQL_ENGINES: Any
DEFAULT_POSTGRESQL_ENGINES: Any
SQLITE_ENGINES: Any
MYSQL_ENGINES: Any
POSTGRESQL_ENGINES: Any
