from typing import Any

from django.template import Node

HAS_PYGMENTS: bool
register: Any

def parse_template(value: Any): ...

class CodeNode(Node):
    language: Any = ...
    nodelist: Any = ...
    name: Any = ...
    def __init__(self, language: Any, nodelist: Any, name: str = ...) -> None: ...
    def render(self, context: Any): ...

def highlight(parser: Any, token: Any): ...
