from typing import Any, Optional

HAS_PYGMENTS: bool
register: Any

def pygments_required(func: Any): ...
def pygments_css(): ...
def generate_pygments_css(path: Optional[Any] = ...) -> None: ...
def get_lexer(value: Any, arg: Any): ...
def colorize(value: Any, arg: Optional[Any] = ...): ...
def colorize_table(value: Any, arg: Optional[Any] = ...): ...
def colorize_noclasses(value: Any, arg: Optional[Any] = ...): ...
