# Generated by Django 3.0.6 on 2020-05-15 07:51

from django.db import migrations

PERMISSIONS = (
    "add_festival",
    "add_meeting",
    "add_meetinguser",
    "change_festival",
    "change_meeting",
    "change_meetinguser",
    "change_sphere",
    "delete_festival",
    "delete_meeting",
    "delete_meetinguser",
    "view_festival",
    "view_meeting",
    "view_meetinguser",
    "view_sphere",
)


def add_sphere_manager(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, __ = Group.objects.get_or_create(name="Sphere Manager")
    permissions = Permission.objects.filter(codename__in=PERMISSIONS)
    group.permissions.set(permissions)


def delete_sphere_manager(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.filter(name="Sphere Manager").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crowd", "0004_add_superuser"),
        ("chronology", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_sphere_manager, delete_sphere_manager)]
