# Generated by Django 3.0.8 on 2020-07-20 15:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowd", "0006_auto_20200709_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth0_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="auth0 id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locale",
            field=models.CharField(default="en", max_length=20, verbose_name="locale"),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="uuid",
            ),
        ),
    ]
