# Generated by Django 3.0.8 on 2020-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0007_locale'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, auth0_id=''), fields=('auth0_id',), name='unique_nonempty_auth0_id'),
        ),
    ]
