# Generated by Django 3.1 on 2020-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0008_add_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
