from typing import Any

from django.db import models
from django_extensions.db.fields import AutoSlugField as AutoSlugField
from django_extensions.db.fields import CreationDateTimeField as CreationDateTimeField
from django_extensions.db.fields import (
    ModificationDateTimeField as ModificationDateTimeField,
)

class TimeStampedModel(models.Model):
    created: Any = ...
    modified: Any = ...
    update_modified: Any = ...
    def save(self, **kwargs: Any) -> None: ...
    class Meta:
        get_latest_by: str = ...
        abstract: bool = ...

class TitleDescriptionModel(models.Model):
    title: Any = ...
    description: Any = ...
    class Meta:
        abstract: bool = ...

class TitleSlugDescriptionModel(TitleDescriptionModel):
    slug: Any = ...
    class Meta:
        abstract: bool = ...

class ActivatorQuerySet(models.query.QuerySet):
    def active(self): ...
    def inactive(self): ...

class ActivatorModelManager(models.Manager):
    def get_queryset(self): ...
    def active(self): ...
    def inactive(self): ...

class ActivatorModel(models.Model):
    INACTIVE_STATUS: int = ...
    ACTIVE_STATUS: int = ...
    STATUS_CHOICES: Any = ...
    status: Any = ...
    activate_date: Any = ...
    deactivate_date: Any = ...
    objects: Any = ...
    class Meta:
        ordering: Any = ...
        abstract: bool = ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
