# Generated by Django 3.0.7 on 2020-06-26 07:12
import common.json_field
import notice_board.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_auto_20200601_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphere',
            name='settings',
            field=common.json_field.JSONField(default=notice_board.models.default_sphere_settings),
        ),
    ]
