# Generated by Django 3.0.7 on 2020-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0004_auto_20200626_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
