# Generated by Django 3.0.7 on 2020-06-25 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice_board", "0005_auto_20200626_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Guild",
            ),
        ),
    ]
