# Generated by Django 3.0.8 on 2020-07-20 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0002_update_default_site"),
        ("notice_board", "0008_add_sphere_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guild",
            options={"verbose_name": "guild", "verbose_name_plural": "guilds"},
        ),
        migrations.AlterModelOptions(
            name="guildmember",
            options={
                "verbose_name": "guild member",
                "verbose_name_plural": "guild members",
            },
        ),
        migrations.AlterModelOptions(
            name="meeting",
            options={"verbose_name": "meeting", "verbose_name_plural": "meetings"},
        ),
        migrations.AlterModelOptions(
            name="sphere",
            options={"verbose_name": "sphere", "verbose_name_plural": "spheres"},
        ),
        migrations.AlterField(
            model_name="guild",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="is public"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="members",
            field=models.ManyToManyField(
                through="notice_board.GuildMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="guild",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="guildmember",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Guild",
                verbose_name="guild",
            ),
        ),
        migrations.AlterField(
            model_name="guildmember",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("member", "Member"),
                    ("admin", "Admin"),
                ],
                max_length=255,
                verbose_name="membership type",
            ),
        ),
        migrations.AlterField(
            model_name="guildmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsphere",
            name="is_open",
            field=models.BooleanField(default=True, verbose_name="is open"),
        ),
        migrations.AlterField(
            model_name="historicalsphere",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="historicalsphere",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.Site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="end_time",
            field=models.DateTimeField(null=True, verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Guild",
                verbose_name="guild",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.TextField(blank=True, null=True, verbose_name="location"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_url",
            field=models.URLField(blank=True, verbose_name="meeting url"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="organizer",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="participants",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="publication_time",
            field=models.DateTimeField(null=True, verbose_name="publication time"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="sphere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notice_board.Sphere",
                verbose_name="sphere",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.DateTimeField(null=True, verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="sphere",
            name="is_open",
            field=models.BooleanField(default=True, verbose_name="is open"),
        ),
        migrations.AlterField(
            model_name="sphere",
            name="managers",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="managers"
            ),
        ),
        migrations.AlterField(
            model_name="sphere",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="sphere",
            name="site",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sphere",
                to="sites.Site",
                verbose_name="site",
            ),
        ),
    ]
