# Generated by Django 3.0.8 on 2020-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0011_auto_20200721_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('planned', 'planned'), ('published', 'published'), ('ongoing', 'ongoing'), ('past', 'past')], default='draft', editable=False, max_length=255),
        ),
    ]
