# Generated by Django 3.0.8 on 2020-07-26 08:06

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0012_meeting_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guild',
            constraint=models.UniqueConstraint(fields=('slug',), name='guild_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='guildmember',
            constraint=models.UniqueConstraint(fields=('guild', 'user'), name='guildmember_unique_guild_and_user'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(guild__isnull=False), fields=('slug', 'guild'), name='meeting_unique_slug_in_guild'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(guild__isnull=True), fields=('slug', 'sphere'), name='meeting_unique_slug_in_sphere'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_time__isnull', True), ('publication_time__isnull', True), ('start_time__isnull', True)), models.Q(('created_at__lte', django.db.models.expressions.F('publication_time')), ('publication_time__lte', django.db.models.expressions.F('start_time')), ('start_time__lt', django.db.models.expressions.F('end_time'))), _connector='OR'), name='meeting_date_times'),
        ),
    ]
