# Generated by Django 3.1 on 2020-08-11 18:00

from django.db import migrations, models

import notice_board.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0013_add_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsphere',
            name='settings',
            field=models.JSONField(default=notice_board.models.default_sphere_settings),
        ),
        migrations.AlterField(
            model_name='sphere',
            name='settings',
            field=models.JSONField(default=notice_board.models.default_sphere_settings),
        ),
    ]
