# Generated by Django 3.1 on 2020-08-29 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notice_board", "0014_alter_json_fields"),
    ]

    operations = [
        migrations.RemoveField(model_name="meeting", name="participants",),
        migrations.AddField(
            model_name="meeting",
            name="participants_limit",
            field=models.IntegerField(default=0, verbose_name="participants limit"),
        ),
    ]
