# Generated by Django 3.1 on 2020-08-23 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice_board', '0014_alter_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants_limit',
            field=models.IntegerField(default=0, verbose_name='participants limit'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting')], max_length=15)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='participated_meetings', through='notice_board.Participant', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
