# Generated by Django 3.1 on 2020-10-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0017_new_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants_limit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='participants limit'),
        ),
    ]
