# Generated by Django 3.1.2 on 2020-10-13 19:53

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0018_auto_20201006_2118'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meeting',
            name='meeting_date_times',
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(check=models.Q(('publication_time__isnull', True), ('start_time__isnull', True), ('end_time__isnull', True), models.Q(('publication_time__lte', django.db.models.expressions.F('start_time')), ('start_time__lt', django.db.models.expressions.F('end_time'))), _connector='OR'), name='meeting_date_times'),
        ),
    ]
