from typing import Any

from .resolver import active_resolver as active_resolver

STORAGE: Any
DELETES: Any
M2M_REMOVE: Any
M2M_CLEAR: Any
UPDATE_OLD: Any

def get_old_handler(sender: Any, instance: Any, **kwargs: Any) -> None: ...
def postsave_handler(sender: Any, instance: Any, **kwargs: Any) -> None: ...
def predelete_handler(sender: Any, instance: Any, **_: Any) -> None: ...
def postdelete_handler(sender: Any, instance: Any, **kwargs: Any) -> None: ...
def merge_pk_maps(obj1: Any, obj2: Any): ...
def merge_qs_maps(obj1: Any, obj2: Any): ...
def m2m_handler(sender: Any, instance: Any, **kwargs: Any) -> None: ...
