from django.contrib.auth.mixins import UserPassesTestMixin

class ModelUserFieldPermissionMixin(UserPassesTestMixin):
    model_permission_user_field: str = ...
    def get_model_permission_user_field(self): ...
    def test_func(self): ...
